message("")
message("---------------------------------------- NLOPT")
message(STATUS "Checking for NLOPT")
if(NOT TARGET NLOPT)
    find_package(NLOPT 2.4.2 QUIET)
    if(NLOPT_FOUND)
        message(" Found NLOPT")
    elseif(${BUILD_DEPENDENCIES})
        execute_process(COMMAND ./InstallNLOPT.sh --prefix ${CMAKE_INSTALL_PREFIX} --setup ${TMP_DIR}
                        WORKING_DIRECTORY ${CMAKE_MODULE_PATH}/scripts
                        RESULT_VARIABLE res)
        if(${res} EQUAL 0)
            set(NLOPT_FOUND TRUE)
        endif()
    endif()
endif()
message(STATUS "NLOPT Done")
